services:
  backend:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CORS_ORIGINS=http://localhost:3000
    develop:
      watch:
        - path: .
          target: /app
          action: sync
          ignore:
            - .venv/
            - __pycache__/
    networks:
      - b-rag-network

  frontend:
    image: b-rag-view:1.0.0
    env_file:
      - ../b-rag-view/.env
    ports:
      - "3000:3000"
    networks:
      - b-rag-network

networks:
  b-rag-network:
    driver: bridge
